[package]
name = "ic-cron"
version = "0.2.4"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2018"
description = "Makes your IC canister pro-active"
license = "MIT"

[dependencies]
ic-cdk = "0.3.1"
ic-cdk-macros = "0.3.1"
serde = "1.0.126"
union-utils = "0.1.1"